default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  username: root
  password: root
  pool: 5

development:
  <<: *default
  database: rails_app

#test:
#  <<: *default
#  database: app_test

production:
  <<: *default
  database: rails_app
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>


